# Site settings
title: Programming, Motherfucker 
name: Rael Max
email: contato@raelmax.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer and fake cyclist.
  Posts about python, javascript and random stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raelmax.github.io" # the base hostname & protocol for your site
twitter_username: raelmax
github_username:  raelmax

# Build settings
markdown: kramdown
