name: Rael Max
description: Feito é melhor que perfeito.
meta_description: "Desenvolvedor de Software na Globo.com. Jogador profissional de peladas esporádicas e sommelier de repositórios do github."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://raelmax.github.io'
google_analytics: 'UA-18745352-2'

# Details for the RSS feed generator
url:            'https://raelmax.github.io'
author:         'Rael Max'
