name: Rael Max
description: Desenvolvedor de software
meta_description: "Desenvolvimento de software."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://raelmax.github.io'
google_analytics: 'UA-18745352-2'

# Details for the RSS feed generator
url:            'https://raelmax.github.io'
author:         'Rael Max'
